// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_bZqjjKsB5S3BQf89T-prX6ZoXXhsj8',
    appId: '1:2878514684:web:b0aab17c44838f59723e79',
    messagingSenderId: '2878514684',
    projectId: 'fooddeliveryapp-e0959',
    authDomain: 'fooddeliveryapp-e0959.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-e0959.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcd9deMNtF_6v9l1Od2raptBqshkO7tBI',
    appId: '1:2878514684:android:c48c76f3e115130c723e79',
    messagingSenderId: '2878514684',
    projectId: 'fooddeliveryapp-e0959',
    storageBucket: 'fooddeliveryapp-e0959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9IYEcLWjBHyXqlDGcgmCPc0NHyxOA9A',
    appId: '1:2878514684:ios:e72fed566df7168c723e79',
    messagingSenderId: '2878514684',
    projectId: 'fooddeliveryapp-e0959',
    storageBucket: 'fooddeliveryapp-e0959.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl9IYEcLWjBHyXqlDGcgmCPc0NHyxOA9A',
    appId: '1:2878514684:ios:e72fed566df7168c723e79',
    messagingSenderId: '2878514684',
    projectId: 'fooddeliveryapp-e0959',
    storageBucket: 'fooddeliveryapp-e0959.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ_bZqjjKsB5S3BQf89T-prX6ZoXXhsj8',
    appId: '1:2878514684:web:540b8ac03cadad87723e79',
    messagingSenderId: '2878514684',
    projectId: 'fooddeliveryapp-e0959',
    authDomain: 'fooddeliveryapp-e0959.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-e0959.firebasestorage.app',
  );
}
